// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_first_250_coins = "CgkI2cvD0dAZEAIQDA"; // <GPGSID>
        public const string achievement_first_25_coins = "CgkI2cvD0dAZEAIQCA"; // <GPGSID>
        public const string achievement_first_5_coins = "CgkI2cvD0dAZEAIQAQ"; // <GPGSID>
        public const string leaderboard_level_3_high_scores = "CgkI2cvD0dAZEAIQBw"; // <GPGSID>
        public const string leaderboard_level_2_high_scores = "CgkI2cvD0dAZEAIQBg"; // <GPGSID>
        public const string leaderboard_level_1_high_scores = "CgkI2cvD0dAZEAIQBQ"; // <GPGSID>
        public const string leaderboard_overall_high_scores = "CgkI2cvD0dAZEAIQAg"; // <GPGSID>
        public const string event_collected_coins = "CgkI2cvD0dAZEAIQBA"; // <GPGSID>
        public const string achievement_first_50_coins = "CgkI2cvD0dAZEAIQCg"; // <GPGSID>
        public const string leaderboard_level_4_high_scores = "CgkI2cvD0dAZEAIQCQ"; // <GPGSID>
        public const string achievement_first_100_coins = "CgkI2cvD0dAZEAIQCw"; // <GPGSID>

}

